### ISSUE TITLE
Bug: creating constant variable with float

### ISSUE THREAD

**Issue by mpvanderschelling** [bessagroup/f3dasm#258]
## Problem

When initializing a constant variable with a float, the following error is raised:

```
Traceback (most recent call last):
  File "/home/martin/Documents/scratchbook/try_hydra/main.py", line 10, in <module>
    e = ExperimentData.from_sampling(domain=domain, sampler='random', n_samples=2)
  File "/home/martin/Documents/GitHub/F3DASM/src/f3dasm/_src/experimentdata/experimentdata.py", line 296, in from_sampling
    experimentdata.sample(sampler=sampler, n_samples=n_samples, seed=seed)
  File "/home/martin/Documents/GitHub/F3DASM/src/f3dasm/_src/experimentdata/experimentdata.py", line 1372, in sample
    sample_data: DataTypes = sampler(
  File "/home/martin/Documents/GitHub/F3DASM/src/f3dasm/_src/design/samplers.py", line 157, in __call__
    return self.get_samples()
  File "/home/martin/Documents/GitHub/F3DASM/src/f3dasm/_src/design/samplers.py", line 126, in get_samples
    samples_constant = self._sample_constant(numsamples=numsamples)
  File "/home/martin/Documents/GitHub/F3DASM/src/f3dasm/_src/design/samplers.py", line 163, in _sample_constant
    samples[:, dim] = param.value
ValueError: could not convert string to float: 'test'
```

**Comment by mpvanderschelling** [comment]
> **Automated triage note (reviewed by maintainer @mpvanderschelling before posting):**
> Code-level check against `develop` (commit `547f0d7`). I reproduced an equivalent scenario on develop. Please correct anything I've gotten wrong.

**Status on `develop`:** Resolved by the samplers refactor.

**Where the relevant code lives now:**
- The cited paths (`src/f3dasm/_src/experimentdata/experimentdata.py`, `src/f3dasm/_src/design/samplers.py`) no longer exist. The equivalent code path is:
  - `src/f3dasm/_src/samplers.py:216-244` — `random_sample_constant_parameters(input_space, n_samples, **kwargs)`.

**Root cause / analysis:**
The original failure was `samples[:, dim] = param.value` (`design/samplers.py:163`) — `samples` was a numpy float array, so assigning a string raised `ValueError: could not convert string to float: 'test'`. On develop the function no longer uses a numpy buffer at all:
```python
def random_sample_constant_parameters(input_space, n_samples, **kwargs):
    samples = {}
    for i in range(n_samples):
        sample_values = {name: param.value for name, param in input_space.items()}
        samples[i] = ExperimentSample(_input_data=sample_values)
    return samples
```
It builds a dict of `ExperimentSample`s and never coerces dtypes, so the constant can be any Python value.

Quick repro on develop:
```python
dom = Domain()
dom.add_constant('label', 'test')
dom.add_float('x', low=0., high=1.)
ed = ExperimentData(domain=dom)
s = create_sampler('random', seed=0); s.arm(data=ed)
ed = s.call(data=ed, n_samples=2)
# Returns ed of len 2; 'label' column = 'test', 'x' column = numeric.
```
No exception.

**Suggested fix (sketch, not a patch):**
- Close as resolved.
- Optional: add `tests/sampling/test_constant_string.py` asserting a string-valued `ConstantParameter` round-trips through `create_sampler('random').call(...)`.

**Recommended action:** Close as resolved.
